version: "3"

services:
  
  redis:
    image: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
      # - 8080:5000
    environment:
      REDIS_HOST: redis
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock